### PR TITLE
Fix to compile with scala-2.11

### PR DESCRIPTION
**Pull request by fancywriter**
Current master can't be published because of
```
 value zipWith is not a member of scala.concurrent.Future[scala.util.Either[L,R]]
```
My mistake, `zipWith` was introduced only in scala-2.12, reimplemented it to be compatible with scala-2.11.

### CODE REVIEW

**Comment by t3hnar** [comment]
strange that travis missed that

**Comment by fancywriter** [comment]
Indeed! https://travis-ci.org/evolution-gaming/scala-tools/jobs/249655853
> Using Scala 2.11.11

But inside sbt session itself:

> [info] Resolving org.scala-lang#scala-library;2.12.2 ...
> [info] Resolving org.scoverage#scalac-scoverage-runtime_2.12;1.3.0 ...
...

and

> [info] Compiling 15 Scala sources to /home/travis/build/evolution-gaming/scala-tools/target/scala-2.12/classes...
> [info] 'compiler-interface' not yet compiled for Scala 2.12.2. Compiling...

It didn't even try to compile for scala-2.11 :( looks like travis bug.

**Comment by t3hnar** [comment]
Accepting this one, @fancywriter could you please fix or report this travis bug ?

**Comment by fancywriter** [comment]
@t3hnar in fact travis itself works fine, was configured wrong - pushed another pull request https://github.com/evolution-gaming/scala-tools/pull/6 :)
Checked this
https://travis-ci.org/fancywriter/scala-tools/builds/253978488
https://travis-ci.org/fancywriter/scala-tools/builds/253978524

Regardless of scala version I put in `build.sbt` now it always takes overridden by travis. By the way, if we want to keep our code compatible for two scala versions (2.11.11 and 2.12.2), it's better to put (default for developer, for IDE and for commands like `sbt compile`) scala version the oldest of we support, 2.11.11 this case, not 2.12. What do you think?

**Comment by t3hnar** [comment]
I think you should always strive to write best code regarding the newest version and then make it compatible with older version. Not visa versus. Thus I propose to keep 2.12 as the default.
